config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/login' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  resources :beneficiaries, only: [:index, :new, :create, :edit, :update]

  resources :beneficiaries, only: [:show] do
    resources :updates, only: [:show, :index, :new] do
      resources :comments, only: [:new, :create]
    end
  end

  resources :updates, only: [:index, :new, :create, :edit, :update]

  resources :comments, only: [:new, :create]

  get '/reports/late_updates' => 'reports#late_updates'

end

app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base
  has_many :updates
  has_many :users, through: :updates
  accepts_nested_attributes_for :updates

  validates :name, presence: true
  validates :id_number, presence: true, uniqueness: true, length: { is: 7 }

  def formatted_date_of_birth
    date_of_birth.strftime("%B %d, %Y")
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
        
    validates :description, presence: true
      
  end

app/models/update.rb
class Update < ActiveRecord::Base
  belongs_to :user
  belongs_to :beneficiary
  has_many :comments

  validates :notes, presence: true
  validates :user_id, presence: true
  validates :beneficiary_id, presence: true
  validates :date, presence: true

  scope :incomplete, -> { where(complete: false) }
  scope :late, -> { where('date < ?', 1.week.ago) }

  def formatted_date
    date.strftime("%B %d, %Y")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :updates
  has_many :beneficiaries, through: :updates
  has_many :comments

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    !!current_user
  end

  private
    def require_logged_in
      redirect_to root_path unless logged_in?
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController
  before_action :set_beneficiary, only: [:show, :edit, :update]
  before_action :require_logged_in

  def index
    @beneficiaries = Beneficiary.all
  end

  def new
    @beneficiary = Beneficiary.new
  end

  def create
    @beneficiary = Beneficiary.new(beneficiary_params)
    if @beneficiary.save
      redirect_to beneficiary_path(@beneficiary), notice: 'Beneficiary was successfully created'
    else
      render :new
    end
  end

  def show
    @message = params[:message] if params[:message]
    @message ||= false
  end

  def edit
  end

  def update
    if @beneficiary.update(beneficiary_params)
      redirect_to beneficiary_path(@beneficiary), notice: 'Beneficiary was successfully updated'
    else
      render :edit
    end
  end

  private

  def set_beneficiary
    @beneficiary = Beneficiary.find(params[:id])
  end

  def beneficiary_params
    params.require(:beneficiary).permit(
      :name,
      :date_of_birth,
      :gender,
      :id_number
    )
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_logged_in
  
    def new
      @comment = Comment.new(update_id: params[:update_id], user_id: session[:user_id])
    end
  
    def create
      @comment = Comment.create(comment_params)
      render json: @comment, status: 201
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(
        :update_id,
        :user_id,
        :description,
        :created_at
      )
    end
  
  end
  

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_logged_in

  def late_updates
    @updates = Update.late.incomplete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    if auth
      @user = User.where(email: auth['info']['email']).first_or_create do |user|
        user.name = auth['info']['name']
        user.password = SecureRandom.hex
      end
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You are now logged in"
    else
      @user = User.find_by(name: params[:user][:name])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user), notice: "You are now logged in"
      else
        redirect_to login_path, notice: "You must login with a valid password"
      end
    end
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update]
  before_action :require_logged_in

  def index
    if params[:beneficiary_id]
      @beneficiary = Beneficiary.find(params[:beneficiary_id])
      @updates = Beneficiary.find(params[:beneficiary_id]).updates
      render json: @updates
    else
      @updates = Update.all
      #render json: @updates
    end
  end

  def new
    if params[:beneficiary_id] && !Beneficiary.exists?(params[:beneficiary_id])
      redirect_to beneficiaries_path, notice: "Beneficiary not found."
    else
      @update = Update.new(beneficiary_id: params[:beneficiary_id])
    end
  end

  def create
    @update = Update.new(update_params)
    if @update.save
      redirect_to beneficiary_update_path(params[:update][:beneficiary_id], @update), notice: 'Note was successfuly created'
      #render json: @update, status: 201
    else
      render :new
    end
  end

  def show
    @message = params[:message] if params[:message]
    @message ||= false
    render json: @update
  end

  def edit
  end

  def update
    if @update.update(update_params)
      redirect_to update_path(@update), notice: 'Note was successfully updated'
    else
      render :edit
    end
  end

  private

  def set_update
    @update = Update.find(params[:id])
  end

  def update_params
    params.require(:update).permit(
      :user_id,
      :beneficiary_id,
      :notes,
      :complete,
      :date
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, only: [:index, :show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user), notice: 'User was successfully created'
      else
        render :new
      end
    end

    def show
      @message = params[:message] if params[:message]
      @message ||= false
    end

  def edit
  end

  def update
    if @user.id == session[:user_id]
      if @user.update(user_params)
        redirect_to user_path(@user), notice: 'User was successfully updated'
      else
        render 'edit'
      end
    else
      redirect_to edit_user_path, notice: 'You can only edit your own user profile'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
        params.require(:user).permit(
          :name,
          :title,
          :email,
          :password,
          :password_confirmation,
          :admin
        )
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/beneficiaries/_form.html.erb
<%= form_for @beneficiary do |f| %>
  <% if @beneficiary.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@beneficiary.errors.count, "error") %> prohibited this beneficiary from being saved:
      </h2>

      <ul>
      <% @beneficiary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields_with_errors">
    <p><%= f.label :name %>:  <%= f.text_field :name %></p>
    
    <p><%= f.label :date_of_birth, "Date of Birth" %>:  <%= f.date_field :date_of_birth %></p>
    
    <p><%= f.label :gender %>:  <%= f.text_field :gender %></p>
    
    <p><%= f.label :id_number %>:  <%= f.number_field :id_number %></p>
    
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/beneficiaries/edit.html.erb
<h1>Edit Beneficiary</h1>

<%= render 'form' %><br>

<%= link_to 'Back to Beneficiary', @beneficiary %>

app/views/beneficiaries/index.html.erb
<%= render '/users/notices' %>

<h1> All Beneficiaries </h1>

<% @beneficiaries.each do |beneficiary| %>
<p> Name: <%= beneficiary.name %>, ID Number: <%= beneficiary.id_number %>
  <%= link_to "See details", beneficiary_path(beneficiary) %></p>
<% end %>

<%= link_to "Create New Beneficiary", new_beneficiary_path %>

app/views/beneficiaries/new.html.erb
<h1>Create Beneficiary</h1>

<%= render 'form' %>

app/views/beneficiaries/show.html.erb
<%= render '/users/notices' %>

  <div class="info">
    <p><strong>Name:</strong> <%= @beneficiary.name %></p>
    <p>Date of Birth: <%= @beneficiary.formatted_date_of_birth if @beneficiary.date_of_birth %></p>
    <p>Gender: <%= @beneficiary.gender %></p>
    <p>ID number: <%= @beneficiary.id_number %></p>
    <p><%= link_to 'Edit Beneficiary Profile', edit_beneficiary_path(@beneficiary) %></p>
    <button id="show-updates" data-id="<%= @beneficiary.id %>">List Case Notes</button>
    <div id="updates" style="margin: 20px"></div>
    <div id="update" style="margin: 40px"></div>
    <div id="commentForm"><%= render "comments/form" %></div>
    <p><%= link_to 'Add New Case Note', new_beneficiary_update_path(@beneficiary) %></p>
    </div>

app/views/comments/_form.html.erb
<%= form_for Comment.new do |f| %>
      
    <div>
      <%= f.hidden_field :user_id %>
    
      <p id="user-id"><%= f.hidden_field :update_id %></p>

      <p><%= f.label "Comment" %>:  <%= f.text_field :description %></p>

    </div>
  
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>

  <div id="newComment"></div>
  
  <script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      //prevent form from submitting the default way
      event.preventDefault();
      var values = $(this).serialize();
 
      var posting = $.post('/comments', values);
 
      posting.done(function(data) {
        var comment = data;
        function Comment(description, date){
          this.description = description;
          this.date = date;
        }
        Comment.prototype.commentDetails = function(){
          return "<p>Comment: " + this.description + " Dated: " + this.date.substring(0,10) + "</p>";
        }
        var c = new Comment(comment["description"], comment["created_at"]);
        $("#update").append(c.commentDetails());
        $("#newComment").append(c.commentDetails());
        $('#commentForm').hide();
      });
    });
  });
</script>

app/views/comments/new.html.erb
<h1>Create Case Note</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CaseManagementMvc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons1.css">
</head>

<body>

    <ul class="navbar">
      <% if current_user %>
        <li class="navbar"><%= link_to "Home", root_path %></li>
        <li class="navbar"><%= link_to "Users", users_path %></li>
        <li class="navbar"><%= link_to "Beneficiaries", beneficiaries_path %></li>
        <li class="navbar"><%= link_to "Case Notes", updates_path %></li>
        <li class="navbar"><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li class="navbar"><%= link_to "Home", root_path %></li>
        <li class="navbar"><%= link_to "Sign Up", new_user_path %></li>
        <li class="navbar"><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>

<%= yield %>

</body>
</html>

app/views/reports/late_updates.erb
<h1> Late Case Notes </h1>

<% @updates.each do |update| %>
<p> Beneficiary: <%= update.beneficiary.name %>,  Date: <%= update.formatted_date %>, Note: <%= update.notes %>, Complete <%= check_box_tag :complete, 1, update.complete %>
  <%= link_to "Edit Note", edit_update_path(update) %></p>
<% end %>

app/views/static_pages/home.html.erb
<p>Welcome to Case Management</p>

app/views/updates/_form.html.erb
<%= form_for @update do |f| %>
  <% if @update.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:
      </h2>

      <ul>
      <% @update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields_with_errors">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
  
    <%= f.hidden_field :beneficiary_id %>
  
    <p><%= f.label "Date" %>:  <%= f.date_field :date %></p>
  
    <p><%= f.label "Notes" %>:  <%= f.text_area :notes %></p>
  
    <p><%= f.label "Complete" %>:  <%= f.check_box :complete %></p>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Edit Note</h1>

<%= render 'form' %><br>

<%= link_to 'Back to Beneficiaires', beneficiaries_path %>

app/views/updates/index.html.erb
<% if @beneficiary.present? %>
  <h1>Case Notes for <%= @beneficiary.name %></h1>
<% else %>
  <h1> All Case Notes </h1>
<% end %>

<% @updates.each do |update| %>
<p> Date: <%= update.formatted_date %>, Note: <%= update.notes %>, Complete <%= check_box_tag :complete, 1, update.complete %>
  <%= link_to "Edit Case Note", edit_update_path(update) %></p>
<% end %>

<% if @beneficiary.present? %>
  <%= link_to "Create New Update", new_beneficiary_update_path %><br>
<% end %>
<%= link_to "View Late Update Report", reports_late_updates_path %>

app/views/updates/new.html.erb
<h1>Create Note</h1>

<%= render 'form' %>

app/views/updates/show.html.erb
<%= render '/users/notices' %>

<h1>Update for <%= @update.beneficiary.name %> </h1>

<div class="info">
    <div id="update" style="margin: 20px">
        <p><%= @update.id %>.  Date: <%= @update.formatted_date %>, Note: <%= @update.notes %>, Complete: <%= @update.complete %></p>
        <% @update.comments.each do |comment| %>
            <p>Comment: <%= comment.description %></p>  
        <% end %>
    </div>
    <%= link_to "Return to Beneficiary", beneficiary_path(@update.beneficiary) %>
</div>

app/views/users/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields_with_errors">
    <p><%= f.label :name %>:  <%= f.text_field :name %></p>
  
    <p><%= f.label :title, "Job Title" %>:  <%= f.text_field :title %></p>
  
    <p><%= f.label :email %>:  <%= f.text_field :email %></p>
  
    <p><%= f.label :password %>:  <%= f.password_field :password %></p>
  
    <p><%= f.label :password_confirmation, "Please confirm your password" %>:  <%= f.password_field :password_confirmation %></p>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_notices.html.erb
<p id="notice"><%= notice %></p>

<% if @message %>
  <div class="errors">
    <p><%= @message %></p>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %><br>

<%= link_to 'Back to User', @user %>

app/views/users/index.html.erb
<h1> All Users </h1>

<% @users.each do |user| %>
<p> Name: <%= user.name %>, Position Title: <%= user.title %>
  <%= link_to "See details", user_path(user) %></p>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'notices' %>

  <div class="info">
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>Job Title:</strong> <%= @user.title %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><%= link_to 'Edit User Profile', edit_user_path(@user) %></p>
  </div>